// Login actions
export const SET_LOGIN = 'SRC/REDUX/LOGIN/SET_LOGIN';
export const SET_LOGOUT = 'SRC/REDUX/LOGIN/SET_LOGOUT';

// request actions
export const CALL_REQUEST = 'SRC/ACTIONS/CALL_REQUEST';
export const START_REQUEST = 'SRC/ACTIONS/START_REQUEST';
export const DONE_REQUEST = 'SRC/ACTIONS/DONE_REQUEST';
